### PR TITLE
Add support for file_via_connection

### PR DESCRIPTION
**Pull request by jkufro**
### Description

This PR adds support for file_via_connection

Below is a short test script that monkey patches this plugin with the new method found in this PR.
```ruby
require "train-awsssm"

module TrainPlugins
  module AWSSSM
    class Connection < Train::Plugins::Transport::BaseConnection
      def file_via_connection(path)
        windows_instance? ? Train::File::Remote::Windows.new(self, path) : Train::File::Remote::Unix.new(self, path)
      end
    end
  end
end

train  = Train.create("awsssm", {
            host:     "i-00000000000000000",
            logger:   Logger.new($stdout, level: :info)
         })
conn   = train.connection

# RHEL:
# puts conn.file('/home/ssm-user/test-file.txt').content

# Windows:
# New-Item "C:\Users\Administrator\test-file.txt" -ItemType File -Value "The first sentence in our file."
puts conn.file('C:\\Users\\Administrator\\test-file.txt').content

conn.close
```

### Issues Resolved

Previously the plugin was not capable of interacting with files through the file_via_connection method. The fix is to choose a platform based on the OS. 

[This link references the train-core remote file resources](https://github.com/inspec/train/tree/master/lib/train/file/remote)

### Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by jkufro** [comment]
@pschaumburg @tecracer-theinen

**Comment by pschaumburg** [comment]
Thank you for pinging us. I've added Thomas for a review.

**Comment by tecracer-theinen** [comment]
Awesome idea. That might actually even fill a need I might get during the next week.

I have looked through some other Train plugins and they sometimes have a bit more complete logic.

Maybe it would be an idea to extend the code for other OS types?

SSH has this one apparently:
```ruby
    def file_via_connection(path, *args)
      if os.aix?
        Train::File::Remote::Aix.new(self, path, *args)
      elsif os.solaris?
        Train::File::Remote::Unix.new(self, path, *args)
      elsif os[:name] == "qnx"
        Train::File::Remote::Qnx.new(self, path, *args)
      elsif os.windows?
        Train::File::Remote::Windows.new(self, path, *args)
      else
        Train::File::Remote::Linux.new(self, path, *args)
      end
    end
```

**Comment by jkufro** [comment]
> Awesome idea. That might actually even fill a need I might get during the next week.
> 
> I have looked through some other Train plugins and they sometimes have a bit more complete logic.
> 
> Maybe it would be an idea to extend the code for other OS types?
> 
> SSH has this one apparently:
> 
> ```ruby
>     def file_via_connection(path, *args)
>       if os.aix?
>         Train::File::Remote::Aix.new(self, path, *args)
>       elsif os.solaris?
>         Train::File::Remote::Unix.new(self, path, *args)
>       elsif os[:name] == "qnx"
>         Train::File::Remote::Qnx.new(self, path, *args)
>       elsif os.windows?
>         Train::File::Remote::Windows.new(self, path, *args)
>       else
>         Train::File::Remote::Linux.new(self, path, *args)
>       end
>     end
> ```

This change is ok with me. I would just note that even though those OS types may be supported at the plugin level there is a possibility that there is not a currently supported installer package for SSM agent for some of these operating systems - although it is a possibility that there are unofficial versions or official versions that may be released in the future. 

https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html

**Comment by tecracer-theinen** [comment]
That's a valid concern. I admit I just went ahead and proposed one of the most complete implementations.

Maybe that code will go away in a future version. Or AWS will publish Aix agents for hybrid environments. We will see :)

Thank you very much for the PR!

**Pull request merged**
